name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ⬇️  NUOVO: esegue la pipeline per creare rio_best_precision.csv
      - name: Generate CSV
        run: python scripts/rio_pipeline_retry.py

      - name: Run tests
        run: |
          set -o pipefail
          pytest -q 2>&1 | tee pytest.log

      - name: Upload failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test_failures
          path: pytest.log
