name: CI

on:
  push:
    branches: [ main, dev, "**/codex-**" ]   # esegue sui push in questi branch
  pull_request:                              # …e su tutte le PR
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona il repository
      - uses: actions/checkout@v4

      # 2. Imposta Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Installa dipendenze
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Esegui PyTest (fallirà se KPI non superati)
      - name: Run tests
        run: pytest -q

      # 5. (Opzionale) Verifica linting con ruff
      - name: Ruff lint
        run: |
          pip install ruff
          ruff .

