name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Run tests
        id: pytest
        continue-on-error: true     # così la job finisce anche se i test falliscono
        run: |
          pytest -q | tee pytest.log
      - name: Upload failures
        if: steps.pytest.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test_failures
          path: pytest.log
      - name: Fail if tests red
        if: steps.pytest.outcome == 'failure'
        run: exit 1
