name: Codex Auto-Fix

# Si attiva solo quando il workflow "CI" termina
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  actions: read            # per scaricare artifact della CI
  contents: write          # per pushare la branch bot
  pull-requests: write     # per aprire la PR

jobs:
  bot:
    # ⬇️  Skip totale se la CI è verde
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    runs-on: ubuntu-latest

    steps:
      # 1 · Checkout del branch che ha fallito la CI
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      # 2 · Scarica pytest.log (se c'è) — non fallisce se manca
      - name: Download test report
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: test_failures
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: .

      # 3 · Ambiente Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install openai pytest

      # 4 · Esegui lo script Codex (se fallisce lo step resta rosso,
      #     ma l'intero job rimane verde grazie a continue-on-error)
      - name: Run Codex patcher
        continue-on-error: true
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/codex_patch.py

      # 5 · Se i test ora passano, crea branch + PR
      - name: Push fix & open PR
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name  "codex-bot"
          git config --global user.email "bot@users.noreply.github.com"
          BR="codex-bot/fix-${{ github.event.workflow_run.head_sha }}"
          git checkout -b "$BR"
          git commit -am "codex: auto-fix KPI tests"
          git push -u origin "$BR"
          gh pr create \
            --title "Codex auto-fix for ${{ github.event.workflow_run.head_sha }}" \
            --body  "Patch generated automatically by Codex." \
            --base  ${{ github.event.workflow_run.head_branch }}
