name: Codex Auto-Fix

# parte SOLO quando il workflow "CI" termina in failure
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    conclusions: [failure]

permissions:
  contents: write          # per pushare la branch
  pull-requests: write     # per aprire la PR

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      # 1 · Checkout del branch che ha fallito
      - name: Checkout failing branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      # 2 · Scarica l'artifact test_failures dal run CI che ha fallito
      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: test_failures
          run-id: ${{ github.event.workflow_run.id }}

      # 3 · Setup Python & deps
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install openai pytest

      # 4 · Lancia lo script che chiede la patch a Codex
      - name: Run Codex patcher
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/codex_patch.py

      # 5 · Se i test ora passano, push su branch bot + PR automatica
      - name: Push fix & open PR
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name  "codex-bot"
          git config --global user.email "bot@users.noreply.github.com"

          BR="codex-bot/fix-${{ github.event.workflow_run.head_sha }}"
          git checkout -b "$BR"
          git commit -am "codex: auto-fix KPI tests"
          git push -u origin "$BR"

          gh pr create \
            --title "Codex auto-fix for ${{ github.event.workflow_run.head_sha }}" \
            --body  "Patch generated automatically by Codex to fix failing KPI tests." \
            --base  ${{ github.event.workflow_run.head_branch }}
