name: Codex Auto-Fix

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    conclusions: [failure]

permissions:
  contents: write
  pull-requests: write

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      # 1 · Checkout il branch che ha fallito
      - name: Checkout failing branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      # 2 · DEBUG: elenca artefatti presenti nel run CI
      - name: List artifacts in failing CI run
        uses: actions/github-script@v7
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
        with:
          script: |
            const run_id   = process.env.RUN_ID;
            const arts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo:  context.repo.repo,
              run_id
            });
            core.info(`Artifacts for run ${run_id}:`);
            for (const a of arts.data.artifacts) {
              core.info(`- ${a.name} (${a.size_in_bytes} bytes)`);
            }

      # 3 · Scarica l'artefatto test_failures dal run CI
      - name: Download test report
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: test_failures
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: .

      # 4 · Setup Python
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - run: pip install openai pytest

      # 5 · Chiede la patch a Codex
      - name: Run Codex patcher
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/codex_patch.py

      # 6 · Se i test ora passano, push branch e apri PR
      - name: Push fix & open PR
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name  "codex-bot"
          git config --global user.email "bot@users.noreply.github.com"

          BR="codex-bot/fix-${{ github.event.workflow_run.head_sha }}"
          git checkout -b "$BR"
          git commit -am "codex: auto-fix KPI tests"
          git push -u origin "$BR"

          gh pr create \
            --title "Codex auto-fix for ${{ github.event.workflow_run.head_sha }}" \
            --body  "Patch generated automatically by Codex to fix failing KPI tests." \
            --base  ${{ github.event.workflow_run.head_branch }}
